# For use with the Rest Client VSCode extension (humao.rest-client)

@baseUrl=http://127.0.0.1:5000

GET {{baseUrl}}

###

GET {{baseUrl}}/test-route

###

POST {{baseUrl}}/test-route
Content-Type: application/json

{ 
    "testkey": "Test value"
}